# renew_before_expiry = 30 days
version = 1.22.0
archive_dir = /etc/letsencrypt/archive/wenshuosc.com
cert = /etc/letsencrypt/live/wenshuosc.com/cert.pem
privkey = /etc/letsencrypt/live/wenshuosc.com/privkey.pem
chain = /etc/letsencrypt/live/wenshuosc.com/chain.pem
fullchain = /etc/letsencrypt/live/wenshuosc.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b6e644433ba6ef299b428029faf33fee
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
pref_challs = dns-01,
