/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminRoleAvatar: typeof import('./components/AdminRoleAvatar.vue')['default']
    CsChatPanel: typeof import('./components/cs/CsChatPanel.vue')['default']
    CsSessionListPanel: typeof import('./components/cs/CsSessionListPanel.vue')['default']
    LoginCard: typeof import('./components/auth/LoginCard.vue')['default']
    LoginWelcomeCelebration: typeof import('./components/auth/LoginWelcomeCelebration.vue')['default']
    MallBrandLogo: typeof import('./components/MallBrandLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrafficChannelNameTag: typeof import('./components/TrafficChannelNameTag.vue')['default']
    UserRegistrationInfoScroll: typeof import('./components/UserRegistrationInfoScroll.vue')['default']
    UserRiskDetailDialog: typeof import('./components/UserRiskDetailDialog.vue')['default']
  }
}
