<!-- 免责声明 -->
<script setup lang="ts">
import DOMPurify from 'dompurify'
import { marked } from 'marked'

useSeoMeta({
  title: 'Disclaimer',
})

// const { webConfig } = useAppStore()

const content = ref(`
## Disclaimer
All information presented on this website is intended for general knowledge and reference. While we strive for accuracy, we make no promises regarding the reliability or completeness of the materials displayed.
### 1. Automated Content Notice
Many elements of this site—including images, text, and quotes—are generated by artificial intelligence. These are algorithmically produced and may not always reflect real-world facts or appropriate context. Users are encouraged to use their own discretion before relying on such content.
### 2. Accuracy and Timeliness
We do not warrant that the information presented—whether human-written or AI-created—is always current, accurate, or complete. Some details may be outdated, speculative, or missing important context.
### 3. Liability Limitation
By using this site, you acknowledge that we are not responsible for any kind of damage, loss, or consequences—whether direct or indirect—arising from the use of any content, including AI-generated material.
### 4. External Website References
Our site may include links to outside resources for your convenience. However, we hold no responsibility for the content, data handling, or practices of any third-party websites.
### 5. Editorial Rights
We retain the right to update, alter, or delete any content on this platform without prior announcement.
### 6. No Endorsements
Mentions of other organizations, services, or products on this site do not imply any endorsement, sponsorship, or partnership unless explicitly stated.
`)

const compiledMarkdown = computed(() => {
  const html = marked.parse(content.value) as string
  if (import.meta.client) {
    return DOMPurify.sanitize(html)
  }
  return html
})
</script>

<template>
  <div class="app-wrapper">
    <div class="app-content py-8">
      <!-- eslint-disable-next-line vue/no-v-html vue/max-attributes-per-line -->
      <div class="legal-content" v-html="compiledMarkdown" />
    </div>
  </div>
</template>
