<!-- 服务条款 -->
<script setup lang="ts">
import DOMPurify from 'dompurify'
import { marked } from 'marked'

useSeoMeta({
  title: 'Terms of Service',
})

// const { webConfig } = useAppStore()

const content = ref(`
## Terms of Service
Welcome! By using this website, you confirm that you’ve read, understood, and accepted the following terms. Please take a moment to go through them.
### 1. Intellectual Property
Everything you see on this website—including images, text, and AI-generated materials—belongs to us or our content partners. You are not permitted to copy, edit, or redistribute any of it without explicit authorization.
### 2. AI Content Disclaimer
This site features content generated by artificial intelligence. Such content is meant for general inspiration or informational use only. We do not guarantee its accuracy, reliability, or relevance. Users should independently verify and interpret the information provided.
### 3. Account Security
If you choose to register, you're responsible for securing your login details. Any activity under your account will be considered your own, so please keep your credentials private.
### 4. Acceptable Use
You agree to use the site in a lawful, respectful manner. Any disruptive, malicious, or unauthorized activity is strictly forbidden.
### 5. Changes to Services
We may update, modify, or discontinue any part of the website or its features at any time without prior warning.
### 6. Legal Jurisdiction
These terms follow the laws of the country or region in which this website is operated. Any legal issues will be resolved under that jurisdiction.
### 7. Limitation of Responsibility
We are not liable for any direct or indirect damages resulting from the use of this website—including but not limited to data loss, financial consequences, or risks associated with AI-generated materials.
`)

const compiledMarkdown = computed(() => {
  const html = marked.parse(content.value) as string
  if (import.meta.client) {
    return DOMPurify.sanitize(html)
  }
  return html
})
</script>

<template>
  <div class="app-wrapper">
    <div class="app-content py-8">
      <!-- eslint-disable-next-line vue/no-v-html vue/max-attributes-per-line -->
      <div class="legal-content" v-html="compiledMarkdown" />
    </div>
  </div>
</template>
