/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $fetch: typeof import('@/spa-shim').$fetch
  const ADMIN_TEST_ACCOUNT_ALIAS: typeof import('./composables/useMallAuth').ADMIN_TEST_ACCOUNT_ALIAS
  const ADMIN_TEST_MALL_PASSWORD: typeof import('./composables/useMallAuth').ADMIN_TEST_MALL_PASSWORD
  const ADMIN_TEST_PHONE: typeof import('./composables/useMallAuth').ADMIN_TEST_PHONE
  const ADMIN_TEST_VERIFY_CODE: typeof import('./composables/useMallAuth').ADMIN_TEST_VERIFY_CODE
  const EffectScope: typeof import('vue').EffectScope
  const ElMessage: typeof import('element-plus/es').ElMessage
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const ensureMallProductsLoaded: typeof import('./composables/useTeaProducts').ensureMallProductsLoaded
  const formatBillAmount: typeof import('./composables/useMallMy').formatBillAmount
  const formatMallOrderTime: typeof import('./composables/useMallOrders').formatMallOrderTime
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getSimulatedLogisticsTrace: typeof import('./composables/useMallOrders').getSimulatedLogisticsTrace
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isAdminTestAccount: typeof import('./composables/useMallAuth').isAdminTestAccount
  const isMallCategoryKey: typeof import('./composables/useTeaProducts').isMallCategoryKey
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizeMallAccount: typeof import('./composables/useMallAuth').normalizeMallAccount
  const normalizeOrderTrackingNumber: typeof import('./composables/useMallOrders').normalizeOrderTrackingNumber
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const orderHasShippedTracking: typeof import('./composables/useMallOrders').orderHasShippedTracking
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCookie: typeof import('@/spa-shim').useCookie
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCustomDevice: typeof import('./composables/useCustomDevice').useCustomDevice
  const useCustomRouting: typeof import('./composables/useCustomRouting').useCustomRouting
  const useDevice: typeof import('./composables/useDevice').useDevice
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMallAuth: typeof import('./composables/useMallAuth').useMallAuth
  const useMallCategories: typeof import('./composables/useTeaProducts').useMallCategories
  const useMallMy: typeof import('./composables/useMallMy').useMallMy
  const useMallOrders: typeof import('./composables/useMallOrders').useMallOrders
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useRuntimeConfig: typeof import('@/spa-shim').useRuntimeConfig
  const useSlots: typeof import('vue').useSlots
  const useState: typeof import('@/spa-shim').useState
  const useTeaProducts: typeof import('./composables/useTeaProducts').useTeaProducts
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { RegisterPayload } from './composables/useMallAuth'
  import('./composables/useMallAuth')
  // @ts-ignore
  export type { MallMySummary, MallAddressItem, MallAddressPayload, MallBankCardItem, MallBillItem, MallBillSummary } from './composables/useMallMy'
  import('./composables/useMallMy')
  // @ts-ignore
  export type { MallOrderStatus, MallPayType, MallPayChannel, MallOrder, SimulatedLogisticsNode } from './composables/useMallOrders'
  import('./composables/useMallOrders')
  // @ts-ignore
  export type { TeaProduct, MallCategoryKey, MallCategoryItem } from './composables/useTeaProducts'
  import('./composables/useTeaProducts')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $fetch: UnwrapRef<typeof import('@/spa-shim')['$fetch']>
    readonly ADMIN_TEST_ACCOUNT_ALIAS: UnwrapRef<typeof import('./composables/useMallAuth')['ADMIN_TEST_ACCOUNT_ALIAS']>
    readonly ADMIN_TEST_MALL_PASSWORD: UnwrapRef<typeof import('./composables/useMallAuth')['ADMIN_TEST_MALL_PASSWORD']>
    readonly ADMIN_TEST_PHONE: UnwrapRef<typeof import('./composables/useMallAuth')['ADMIN_TEST_PHONE']>
    readonly ADMIN_TEST_VERIFY_CODE: UnwrapRef<typeof import('./composables/useMallAuth')['ADMIN_TEST_VERIFY_CODE']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly ElMessage: UnwrapRef<typeof import('element-plus/es')['ElMessage']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly ensureMallProductsLoaded: UnwrapRef<typeof import('./composables/useTeaProducts')['ensureMallProductsLoaded']>
    readonly formatBillAmount: UnwrapRef<typeof import('./composables/useMallMy')['formatBillAmount']>
    readonly formatMallOrderTime: UnwrapRef<typeof import('./composables/useMallOrders')['formatMallOrderTime']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getSimulatedLogisticsTrace: UnwrapRef<typeof import('./composables/useMallOrders')['getSimulatedLogisticsTrace']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isAdminTestAccount: UnwrapRef<typeof import('./composables/useMallAuth')['isAdminTestAccount']>
    readonly isMallCategoryKey: UnwrapRef<typeof import('./composables/useTeaProducts')['isMallCategoryKey']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeMallAccount: UnwrapRef<typeof import('./composables/useMallAuth')['normalizeMallAccount']>
    readonly normalizeOrderTrackingNumber: UnwrapRef<typeof import('./composables/useMallOrders')['normalizeOrderTrackingNumber']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly orderHasShippedTracking: UnwrapRef<typeof import('./composables/useMallOrders')['orderHasShippedTracking']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCookie: UnwrapRef<typeof import('@/spa-shim')['useCookie']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCustomDevice: UnwrapRef<typeof import('./composables/useCustomDevice')['useCustomDevice']>
    readonly useCustomRouting: UnwrapRef<typeof import('./composables/useCustomRouting')['useCustomRouting']>
    readonly useDevice: UnwrapRef<typeof import('./composables/useDevice')['useDevice']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMallAuth: UnwrapRef<typeof import('./composables/useMallAuth')['useMallAuth']>
    readonly useMallCategories: UnwrapRef<typeof import('./composables/useTeaProducts')['useMallCategories']>
    readonly useMallMy: UnwrapRef<typeof import('./composables/useMallMy')['useMallMy']>
    readonly useMallOrders: UnwrapRef<typeof import('./composables/useMallOrders')['useMallOrders']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('@/spa-shim')['useRuntimeConfig']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useState: UnwrapRef<typeof import('@/spa-shim')['useState']>
    readonly useTeaProducts: UnwrapRef<typeof import('./composables/useTeaProducts')['useTeaProducts']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}