/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./components/my/address/index.vue')['default']
    AppTabbar: typeof import('./components/App/AppTabbar.vue')['default']
    BankCard: typeof import('./components/my/bank-card/index.vue')['default']
    Banner: typeof import('./components/index/banner.vue')['default']
    BannerM: typeof import('./components/index/banner-m.vue')['default']
    Bill: typeof import('./components/my/bill/index.vue')['default']
    CardPackage: typeof import('./components/my/card-package/index.vue')['default']
    CardPackageSection: typeof import('./components/my/CardPackageSection.vue')['default']
    Create: typeof import('./components/order/create.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IndexM: typeof import('./components/list/index-m.vue')['default']
    InstallmentZone: typeof import('./components/index/installment-zone.vue')['default']
    InstallmentZoneM: typeof import('./components/index/installment-zone-m.vue')['default']
    List: typeof import('./components/index/list.vue')['default']
    ListM: typeof import('./components/index/list-m.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    MallProductDetailGallery: typeof import('./components/mall/MallProductDetailGallery.vue')['default']
    My: typeof import('./components/my/index.vue')['default']
    Order: typeof import('./components/my/order/index.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
