/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressEditorDialog: typeof import('./components/my/address/AddressEditorDialog.vue')['default']
    AppBeianFooter: typeof import('./components/App/AppBeianFooter.vue')['default']
    AppTabbar: typeof import('./components/App/AppTabbar.vue')['default']
    CardPackageClaimDialog: typeof import('./components/my/card-package/dialogs/CardPackageClaimDialog.vue')['default']
    CardPackageContractDialogs: typeof import('./components/my/card-package/dialogs/CardPackageContractDialogs.vue')['default']
    CardPackageEmergencyDialog: typeof import('./components/my/card-package/dialogs/CardPackageEmergencyDialog.vue')['default']
    CardPackagePreClaimDialog: typeof import('./components/my/card-package/dialogs/CardPackagePreClaimDialog.vue')['default']
    CardPackageSection: typeof import('./components/my/CardPackageSection.vue')['default']
    Create: typeof import('./components/order/create.vue')['default']
    CsKefuImageDialog: typeof import('./components/cs/CsKefuImageDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HomeBannerMobile: typeof import('./components/index/HomeBannerMobile.vue')['default']
    HomeListMobile: typeof import('./components/index/HomeListMobile.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    InstallmentZoneMobile: typeof import('./components/index/InstallmentZoneMobile.vue')['default']
    LakalaPaySheet: typeof import('./components/payment/LakalaPaySheet.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    MallListMobile: typeof import('./components/list/MallListMobile.vue')['default']
    MallProductDetailGallery: typeof import('./components/mall/MallProductDetailGallery.vue')['default']
    MallSearchMobile: typeof import('./components/search/MallSearchMobile.vue')['default']
    MyAddressMobile: typeof import('./components/my/address/MyAddressMobile.vue')['default']
    MyBankCardMobile: typeof import('./components/my/bank-card/MyBankCardMobile.vue')['default']
    MyBillMobile: typeof import('./components/my/bill/MyBillMobile.vue')['default']
    MyCardPackageMobile: typeof import('./components/my/card-package/MyCardPackageMobile.vue')['default']
    MyCenterMobile: typeof import('./components/my/MyCenterMobile.vue')['default']
    MyOrderMobile: typeof import('./components/my/order/MyOrderMobile.vue')['default']
    PrivacyPolicyContent: typeof import('./components/my/privacy-policy/PrivacyPolicyContent.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrafficCreditLeadDialog: typeof import('./components/traffic/TrafficCreditLeadDialog.vue')['default']
    UserAgreementContent: typeof import('./components/my/user-agreement/UserAgreementContent.vue')['default']
  }
}
